### ISSUE TITLE
V20 file created empty JSON topic field and crashed filewriter

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#573] opened 2019-11-29 17:31 UTC
When using the file generated from the nexus-constructor, the filewriter crashed because a topic field was blank. We should find out what caused this and see if we can reproduce it then fix it.

**Comment by rerpha** [comment] 2019-12-16 15:00
create a filewriter issue as well - this is an issue in both. an empty string should not cause it to segfault/crash

**Comment by kmurica** [comment] 2021-02-23 15:22
Might become a non-issue with https://github.com/ess-dmsc/nexus-constructor/issues/840 if the problem is only for file writing from nexus constructor?

**Comment by matthew-d-jones** [comment] 2021-02-25 13:50
The problem was in the output JSON, the direct Filewriter control wasn't used. However the entire data model and JSON writing code has been replaced since this ticket was created, so I will close it.

**Closed by matthew-d-jones** 2021-02-25 13:50 UTC
Labels: bug
