### ISSUE TITLE
Automatically set dtype of field based on nexus definition when name is filled out

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#668] opened 2020-03-09 16:30 UTC
Currently static and defaults to "byte" which is annoying. Would be helpful seeing as we have tooltips if we could set the dtype as specified in the nexus documentation when the name of the field is changed to something in the documentation. 

If field name does not match one in documentation then default to `double`.

**Comment by rerpha** [comment] 2020-03-13 10:44
We are going to need to convert the aliases like NXCHAR to the UI combo box values so we can populate what dtype the field needs to be.

**Comment by rerpha** [comment] 2020-04-22 11:52
OK, we shoudl probably do this when a user chooses something from the autocompleter, i suspect there is a signal to notify when a suggestion has been picked.

**Comment by matthew-d-jones** [comment] 2021-02-26 11:33
Duplicate of #364

**Closed by matthew-d-jones** 2021-02-26 11:33 UTC
Labels: enhancement
