### ISSUE TITLE
Cannot reorder without deleting and readding transformations

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#666] opened 2020-03-09 16:27 UTC
Currently not possible, the drag-and-drop stuff should be added again so transformations can be reordered.

We should have a think about whether a user should be able to move a transformation from one component to another as well.

**Comment by kmurica** [comment] 2021-02-23 14:08
"the drag-and-drop stuff should be **added again** so transformations can be reordered."

We need to figure out why it was removed in the first place and what PR was this removal related to?

**Comment by matthew-d-jones** [comment] 2021-02-26 11:36
Duplicate of #372 
I have added more details to that ticket.

**Closed by matthew-d-jones** 2021-02-26 11:36 UTC
Labels: enhancement
