### ISSUE TITLE
NC-specific attrs are not blacklisted correctly

### ISSUE THREAD

**Issue by rerpha** [ess-dmsc/nexus-constructor#660] opened 2020-03-09 13:28 UTC
`NCdependee_of` and so on are not blacklisted correctly and are directly editable in the `attrs` interface of a field. 

They should not be editable through this interface as they'll cause interference with the UI.

**Comment by rerpha** [comment] 2020-03-12 16:23
I am having some trouble reproducing this. @matthew-d-jones do you remember how this occurred and how to get to the attrs that should be blacklisted?

**Comment by matthew-d-jones** [comment] 2020-04-22 09:22
Unable to reproduce so closing ticket.

**Closed by matthew-d-jones** 2020-04-22 09:22 UTC
Labels: bug
